### ISSUE TITLE
Fresh pod install fails on current expokit-32 branch

### ISSUE THREAD

**Issue by tanx** [lightninglabs/lightning-app#1116]
Running `pod install` under `mobile/ios` fails with an empty `mobile/ios/Pods` directory with the following output:

```
Tankreds-MacBook-Pro:ios tanx$ pod install --repo-update
Ignoring eventmachine-1.2.7 because its extensions are not built.  Try: gem pristine eventmachine --version 1.2.7
Ignoring ffi-1.9.25 because its extensions are not built.  Try: gem pristine ffi --version 1.9.25
Ignoring http_parser.rb-0.6.0 because its extensions are not built.  Try: gem pristine http_parser.rb --version 0.6.0
Updating local specs repositories
  $ /usr/local/bin/git -C /Users/tanx/.cocoapods/repos/master fetch origin
  --progress
  remote: Enumerating objects: 84885, done.
  remote: Counting objects: 100% (84885/84885), done.
  remote: Compressing objects: 100% (217/217), done.
  remote: Total 330758 (delta 84695), reused 84755 (delta 84654), pack-reused 245873
  Empfange Objekte: 100% (330758/330758), 36.80 MiB | 4.74 MiB/s, Fertig.
  Löse Unterschiede auf: 100% (196930/196930), abgeschlossen mit 30905 lokalen Objekten.
  Von https://github.com/CocoaPods/Specs
     6fdbeaff93c..106991d02b6  master     -> origin/master
   * [neuer Branch]            indexes    -> origin/indexes
  $ /usr/local/bin/git -C /Users/tanx/.cocoapods/repos/master rev-parse
  --abbrev-ref HEAD
  master
  $ /usr/local/bin/git -C /Users/tanx/.cocoapods/repos/master reset --hard
  origin/master
  Checke Dateien aus: 100% (25943/25943), Fertig.
  HEAD ist jetzt bei 106991d02b6 [Add] HyperwalletSDK 1.0.0-beta02
warning: Ungenaue Erkennung für Umbenennungen wurde aufgrund zu vieler Dateien
übersprungen.
warning: Sie könnten die Variable diff.renameLimit auf mindestens 25206 setzen und den Befehl
erneut versuchen.

CocoaPods 1.7.0.rc.1 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.7.0.rc.1

Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `EXAdsAdMob` from `../node_modules/expo-ads-admob/ios`
Fetching podspec for `EXAppAuth` from `../node_modules/expo-app-auth/ios`
Fetching podspec for `EXAppLoaderProvider` from `../node_modules/expo-app-loader-provider/ios`
Fetching podspec for `EXBackgroundFetch` from `../node_modules/expo-background-fetch/ios`
Fetching podspec for `EXBarCodeScanner` from `../node_modules/expo-barcode-scanner/ios`
Fetching podspec for `EXBarCodeScannerInterface` from `../node_modules/expo-barcode-scanner-interface/ios`
Fetching podspec for `EXCamera` from `../node_modules/expo-camera/ios`
Fetching podspec for `EXCameraInterface` from `../node_modules/expo-camera-interface/ios`
Fetching podspec for `EXConstants` from `../node_modules/expo-constants/ios`
Fetching podspec for `EXConstantsInterface` from `../node_modules/expo-constants-interface/ios`
Fetching podspec for `EXContacts` from `../node_modules/expo-contacts/ios`
Fetching podspec for `EXCore` from `../node_modules/expo-core/ios`
Fetching podspec for `EXErrors` from `../node_modules/expo-errors/ios`
Fetching podspec for `EXFaceDetectorInterface` from `../node_modules/expo-face-detector-interface/ios`
Fetching podspec for `EXFileSystem` from `../node_modules/expo-file-system/ios`
Fetching podspec for `EXFileSystemInterface` from `../node_modules/expo-file-system-interface/ios`
Fetching podspec for `EXFont` from `../node_modules/expo-font/ios`
Fetching podspec for `EXFontInterface` from `../node_modules/expo-font-interface/ios`
Fetching podspec for `EXGL` from `../node_modules/expo-gl/ios`
Fetching podspec for `EXGL-CPP` from `../node_modules/expo-gl-cpp/cpp`
Fetching podspec for `EXGoogleSignIn` from `../node_modules/expo-google-sign-in/ios`
Fetching podspec for `EXImageLoaderInterface` from `../node_modules/expo-image-loader-interface/ios`
Fetching podspec for `EXLocalAuthentication` from `../node_modules/expo-local-authentication/ios`
Fetching podspec for `EXLocalization` from `../node_modules/expo-localization/ios`
Fetching podspec for `EXLocation` from `../node_modules/expo-location/ios`
Fetching podspec for `EXMediaLibrary` from `../node_modules/expo-media-library/ios`
Fetching podspec for `EXPermissions` from `../node_modules/expo-permissions/ios`
Fetching podspec for `EXPermissionsInterface` from `../node_modules/expo-permissions-interface/ios`
Fetching podspec for `EXPrint` from `../node_modules/expo-print/ios`
Fetching podspec for `EXReactNativeAdapter` from `../node_modules/expo-react-native-adapter/ios`
Fetching podspec for `EXSMS` from `../node_modules/expo-sms/ios`
Fetching podspec for `EXSegment` from `../node_modules/expo-analytics-segment/ios`
Fetching podspec for `EXSensors` from `../node_modules/expo-sensors/ios`
Fetching podspec for `EXSensorsInterface` from `../node_modules/expo-sensors-interface/ios`
Fetching podspec for `EXTaskManager` from `../node_modules/expo-task-manager/ios`
Fetching podspec for `EXTaskManagerInterface` from `../node_modules/expo-task-manager-interface/ios`
Pre-downloading: `ExpoKit` from `http://github.com/expo/expo.git`, tag `ios/2.10.2`
Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `React` from `../node_modules/react-native`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Fetching podspec for `yoga` from `../node_modules/react-native/ReactCommon/yoga`
Downloading dependencies
Installing Amplitude-iOS (3.14.1)
Installing Analytics (3.6.10)
Installing AppAuth (0.95.0)
Installing Bolts (1.9.0)
Installing Branch (0.24.2)
Installing CocoaLumberjack (3.2.1)
Installing Crashlytics (3.12.0)
Installing DoubleConversion (1.1.6)
Installing EXAdsAdMob (2.0.0)
Installing EXAppAuth (2.0.0)
Installing EXAppLoaderProvider (1.0.0)
Installing EXBackgroundFetch (1.0.0)
Installing EXBarCodeScanner (2.0.0)
Installing EXBarCodeScannerInterface (2.0.0)
Installing EXCamera (2.0.0)
Installing EXCameraInterface (2.0.0)
Installing EXConstants (2.0.1)
Installing EXConstantsInterface (2.0.0)
Installing EXContacts (2.0.0)
Installing EXCore (2.0.2)
Installing EXErrors (1.0.0)
Installing EXFaceDetectorInterface (2.0.0)
Installing EXFileSystem (2.0.0)
Installing EXFileSystemInterface (2.0.0)
Installing EXFont (2.0.0)
Installing EXFontInterface (2.0.0)
Installing EXGL (2.0.0)
Installing EXGL-CPP (2.0.0)
Installing EXGoogleSignIn (2.0.0)
Installing EXImageLoaderInterface (2.0.0)
Installing EXLocalAuthentication (2.0.0)
Installing EXLocalization (2.0.0)
Installing EXLocation (2.0.1)
Installing EXMediaLibrary (2.0.0)
Installing EXPermissions (2.0.0)
Installing EXPermissionsInterface (2.0.0)
Installing EXPrint (2.0.0)
Installing EXReactNativeAdapter (2.0.0)
Installing EXSMS (2.0.0)
Installing EXSegment (2.0.0)
Installing EXSensors (2.0.0)
Installing EXSensorsInterface (2.0.0)
Installing EXTaskManager (1.0.0)
Installing EXTaskManagerInterface (1.0.0)
Installing ExpoKit (32.0.0)
Installing FBAudienceNetwork (4.99.0)
Installing FBSDKCoreKit (4.38.1)
Installing FBSDKLoginKit (4.38.1)
Installing FBSDKShareKit (4.38.1)
Installing Fabric (1.9.0)
Installing Folly (2016.10.31.00)
Installing GTMSessionFetcher (1.2.1)
Installing Google-Maps-iOS-Utils (2.1.0)
Installing Google-Mobile-Ads-SDK (7.22.0)
Installing GoogleMaps (2.5.0)
Installing GoogleSignIn (4.4.0)
Installing GoogleToolboxForMac (2.2.0)
Installing JKBigInteger2 (0.0.5)
Installing React (0.57.1)
Installing boost-for-react-native (1.63.0)
Installing glog (0.3.5)
Installing lottie-ios (2.5.2)
Installing yoga (0.57.1.React)
Generating Pods project
[!] An error occurred while processing the post-install hook of the Podfile.

undefined method `native_target' for <Pod::PodTarget name=Amplitude-iOS >:Pod::PodTarget

/Users/tanx/Projects/lightninglabs/lightning-app/mobile/ios/Podfile:137:in `block (4 levels) in from_ruby'
/Users/tanx/Projects/lightninglabs/lightning-app/mobile/ios/Podfile:121:in `each'
/Users/tanx/Projects/lightninglabs/lightning-app/mobile/ios/Podfile:121:in `block (3 levels) in from_ruby'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-core-1.6.1/lib/cocoapods-core/podfile.rb:179:in `post_install!'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:701:in `run_podfile_post_install_hook'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:689:in `block in run_podfile_post_install_hooks'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:145:in `message'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:688:in `run_podfile_post_install_hooks'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:211:in `block in generate_pods_project'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:208:in `generate_pods_project'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:139:in `install!'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/command/install.rb:48:in `run'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:52:in `run'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/bin/pod:55:in `<top (required)>'
/usr/local/Cellar/cocoapods/1.6.1/libexec/bin/pod:22:in `load'
/usr/local/Cellar/cocoapods/1.6.1/libexec/bin/pod:22:in `<main>'
```

**Comment by halseth** [comment]
Can be fixed by installing `cocoapods v1.5.3`.

I also had to update `EXCore` to get the build working:
```
pod repo update
pod update EXCore
pod install --verbose
```

**Comment by tanx** [comment]
@halseth cool thanks. How did you downgrade to `cocoapods v1.5.3`? Using home brew?

**Comment by halseth** [comment]
Uninstalled brew version, then installed using gem: https://github.com/CocoaPods/CocoaPods/issues/8138#issuecomment-461911976

**Comment by tanx** [comment]
@halseth awesome thanks. Got it working.
