### ISSUE TITLE
no such file or directory, open '/home/roberto/.lnd/admin.macaroon'

### ISSUE THREAD

**Issue by roberto68** [lightninglabs/lightning-app#120]
after update I'm having this error. I have the directory ` .lnd ` but the file ` admin.macaroon ` is not present.

I update from  ` git pull `, rebuild ` npm run setup `

here's the full err log:
` 
[webpack] Building...
[electron] [09:41:10.129] [error] lnd: either bitcoin.active or litecoin.active must be set to 1 (true)
[electron] 
[electron] Caught Main Process Error: { Error: ENOENT: no such file or directory, open '/home/roberto/.lnd/admin.macaroon'
[electron]     at Error (native)
[electron]     at Object.fs.openSync (fs.js:640:18)
[electron]     at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
[electron]     at Object.fs.readFileSync (fs.js:508:33)
[electron]     at Object.fs.readFileSync (ELECTRON_ASAR.js:506:29)
[electron]     at Timeout.<anonymous> (/home/roberto/bin/lightning-app/apps/desktop/main.dev.js:202:30)
[electron]     at Timeout.wrapper (timers.js:425:11)
[electron]     at tryOnTimeout (timers.js:232:11)
[electron]     at Timer.listOnTimeout (timers.js:202:5)
[electron]   errno: -2,
[electron]   code: 'ENOENT',
[electron]   syscall: 'open',
[electron]   path: '/home/roberto/.lnd/admin.macaroon' }
[electron] [09:41:10.542] [error] Main Process: Error: ENOENT: no such file or directory, open '/home/roberto/.lnd/admin.macaroon'
[webpack] webpack built 17d8ea299c082500b5bb in 8834ms
`

**Comment by roberto68** [comment]
after update this error vanishes
