### ISSUE TITLE
Failed to Load GRPC module

### ISSUE THREAD

**Issue by prahaladbelavadi** [lightninglabs/lightning-app#143]
### Description
After `npm run setup` and on running `npm start`, electron throws the following error

``
Uncaught Exception:
Error: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: electron-v1.4-darwin-x64-unknown
Found: [node-v57-darwin-x64-unknown]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module '/Users/prahaladbelavadi/Documents/grey/trial/Zap-lightning/lightning-app/apps/desktop/node_modules/grpc/src/node/extension_binary/electron-v1.4-darwin-x64-unknown/grpc_node.node'
    at Object.<anonymous> (/Users/prahaladbelavadi/Documents/grey/trial/Zap-lightning/lightning-app/apps/desktop/node_modules/grpc/src/grpc_extension.js:44:17)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/prahaladbelavadi/Documents/grey/trial/Zap-lightning/lightning-app/apps/desktop/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/prahaladbelavadi/Documents/grey/trial/Zap-lightning/lightning-app/apps/desktop/node_modules/grpc/src/client.js:38:12)
``

### Steps to reproduce the behavior

Post cloning the repository, run `npm run setup` and then `npm install`
I tried `npm rebuild`, but it doesn't do much.

### Expected behavior

Well, I was hoping the app would start

### Actual behavior
Electron throws up an error

### Screenshot and/or logs if applicable
<img width="420" alt="screen shot 2018-01-15 at 1 55 03 pm" src="https://user-images.githubusercontent.com/16673094/34933496-1467c7d6-f9fd-11e7-8ecc-1fe801a9674a.png">

**Comment by Roasbeef** [comment]
This isn't the zap repo.
