### ISSUE TITLE
Panic when "Attempting to bootstrap with: Authenticated Channel Graph"

### ISSUE THREAD

**Issue by rick-kln** [lightninglabs/lightning-app#155]
### Description

Had a couple of channels open and things were working fine, then I closed the laptop and when I came back to the app it was not syncing anymore and there was a panic in the logs. The panic occurs everytime when restarting the app now.

### Steps to reproduce the behavior

1. Checkout `commit 159e7f3acc600f35596e8673ecfad2837f1a26ed (HEAD -> master, tag: v0.1.4-alpha, origin/master, origin/HEAD)`
2. Package the app with `npm run package-electron`
3. Run the app
4. Send funds to the app
5. Open some channels
6. Sleep your computer for a while and then quit the app
7. Re-open the app

### Expected behavior

It syncs and doesn't panic.

### Actual behavior

It panics.

### Screenshot and/or logs if applicable

```
lnd: 2018-01-20 10:20:43.800 [INF] NTFN: New spend subscription: utxo=7f32d3deb556b25e1734b7d96c1e27f064f28ebc2abe65b36c41a2906d56165a:0 2018-01-20 10:20:43.800 [INF] LNWL: Close observer for ChannelPoint(7f32d3deb556b25e1734b7d96c1e27f064f28ebc2abe65b36c41a2906d56165a:0) active 2018-01-20 10:20:43.800 [INF] DISC: Authenticated Gossiper is starting
lnd: 2018-01-20 10:20:43.800 [INF] NTFN: New block epoch subscription
lnd: 2018-01-20 10:20:43.800 [INF] CRTR: FilteredChainView starting
lnd: 2018-01-20 10:20:43.802 [INF] CRTR: Filtering chain using 1 channels active 2018-01-20 10:20:43.802 [INF] CRTR: Prune tip for Channel Graph: height=1259618, hash=000000000000029b7027c4d6a15f79c7dcdc5732b35bac9a612fbed99907119e
lnd: 2018-01-20 10:20:43.802 [INF] CRTR: Syncing channel graph from height=1259618 (hash=000000000000029b7027c4d6a15f79c7dcdc5732b35bac9a612fbed99907119e) to height=1259686 (hash=00000000c92c1a317ce549aaa25922a75bcb97f4e270cb02b9140f1920576f06)
lnd: 2018-01-20 10:20:43.803 [INF] CRTR: Block 00000000000007767ee00a31420a8bfec86a54def509cbeba67bc4f7e7693d83 (height=1259619) closed 0 channels
lnd: 2018-01-20 10:20:43.803 [INF] CRTR: Block 000000009eb71cd3e66d9b4f4e9ffbe5d7699effcb909968c1600e23a45bcd0b (height=1259620) closed 0 channels
lnd: 2018-01-20 10:20:43.804 [INF] CRTR: Block 000000000013e6c159a71eac4a8e2dd23790d3b365a4e1d8926932c8132fc503 (height=1259621) closed 0 channels
lnd: 2018-01-20 10:20:43.804 [INF] CRTR: Block 00000000000005d97220420c93938b4f3cfca28a6f26cd97bc648d12a7989e59 (height=1259622) closed 0 channels
lnd: 2018-01-20 10:20:43.805 [INF] CRTR: Block 00000000000000282456fa212709d99478a6fa9e5a63141412c81e6c9ff32e88 (height=1259623) closed 0 channels
lnd: 2018-01-20 10:20:43.806 [INF] CRTR: Block 000000000000082ada983792f012e83c7ed5c88006abcb54f4285f6cce1a7e5e (height=1259624) closed 0 channels
lnd: 2018-01-20 10:20:43.806 [INF] CRTR: Block 00000000000008068c808c280a01e84318168750cd6bbb10414f644474eb54e6 (height=1259625) closed 0 channels
lnd: 2018-01-20 10:20:43.807 [INF] CRTR: Block 00000000000ea3cff0f88cdd28f8a46cb0fa094f318315f3d5132368a52785b0 (height=1259626) closed 0 channels
lnd: 2018-01-20 10:20:43.807 [INF] CRTR: Block 00000000000001dd5f24d4bfa72861e00ebac32c1194edde7e4aeae5f8e05b70 (height=1259627) closed 0 channels
lnd: 2018-01-20 10:20:43.808 [INF] CRTR: Block 0000000052744ecd749bae3ab7d7739b0f6dfac0150849e19b29e25beab88d9b (height=1259628) closed 0 channels
lnd: 2018-01-20 10:20:43.808 [INF] CRTR: Block 000000000000053204b7fc91ee539f7385709687c0cc34f351f38ec9a275b926 (height=1259629) closed 0 channels
lnd: 2018-01-20 10:20:43.809 [INF] CRTR: Block 00000000000004b7f4903c6a83027f54c825f666d74b29cdc7cba754b84a4328 (height=1259630) closed 0 channels
lnd: 2018-01-20 10:20:43.809 [INF] CRTR: Block 0000000031f1e0e3b5aa7ed69f6181e45e89ae7908941304486be361199f4679 (height=1259631) closed 0 channels
lnd: 2018-01-20 10:20:43.810 [INF] CRTR: Block 00000000000007f32df205ed98d47539128d8c35855ace2369461b8de2db780e (height=1259632) closed 0 channels
lnd: 2018-01-20 10:20:43.810 [INF] CRTR: Block 000000004d249d4c47e02c28318959bdafc54d71fa9b7014f53f3ee497a06da9 (height=1259633) closed 0 channels
lnd: 2018-01-20 10:20:43.811 [INF] CRTR: Block 00000000000006e6514f6c7f8f5574907214385997216981a23c2e1543a6ab58 (height=1259634) closed 0 channels
lnd: 2018-01-20 10:20:43.811 [INF] CRTR: Block 000000000000052a6995685d07c42e7147ad22a67f006e97a87d63e1a2c82dad (height=1259635) closed 0 channels
lnd: 2018-01-20 10:20:43.812 [INF] CRTR: Block 0000000000000204de95ea837a7d23d603560a2766be37ed6909ff225294863e (height=1259636) closed 0 channels
lnd: 2018-01-20 10:20:43.812 [INF] CRTR: Block 000000000000078acf61835ce9c53b075894a0a7aa56c3f7025ba937e59d6d76 (height=1259637) closed 0 channels
lnd: 2018-01-20 10:20:43.813 [INF] CRTR: Block 000000000000064eaf944be310961915a173d3fb0244e06e3a331e73b73d1891 (height=1259638) closed 0 channels
lnd: 2018-01-20 10:20:43.813 [INF] CRTR: Block 00000000000001a257c5537f14016ba975c4a6c90ab1d62b8acc97e6bbad2497 (height=1259639) closed 0 channels
lnd: 2018-01-20 10:20:43.814 [INF] CRTR: Block 000000000000080abaf396243cfac562c3aa10965092d195be5db164338ed5e3 (height=1259640) closed 0 channels
lnd: 2018-01-20 10:20:43.814 [INF] CRTR: Block 000000000000074e17e87796b45883f1428c384d60788ce26bba65470629f452 (height=1259641) closed 0 channels
lnd: 2018-01-20 10:20:43.815 [INF] CRTR: Block 0000000000000382bd15f39bd0323fdb7d62cc988906283a785fc22463dcbfd7 (height=1259642) closed 0 channels
lnd: 2018-01-20 10:20:43.815 [INF] CRTR: Block 000000000000062a83291752eca05db413c978883b3f3afea794866cbe9cd9b3 (height=1259643) closed 0 channels
lnd: 2018-01-20 10:20:43.816 [INF] CRTR: Block 00000000000002b8eb08fedb3f9f87a1026b63aeeaa4148b413f5b924c44d700 (height=1259644) closed 0 channels
lnd: 2018-01-20 10:20:43.816 [INF] CRTR: Block 00000000f5d30317468e1772133ac38b416aca9ba860c2be54db0c3ceb9e232b (height=1259645) closed 0 channels
lnd: 2018-01-20 10:20:43.817 [INF] CRTR: Block 00000000000005c96c501f6ab2a465e279b268589e6aee394f58dd33952bcf02 (height=1259646) closed 0 channels
lnd: 2018-01-20 10:20:43.817 [INF] CRTR: Block 000000000000064ac96ed9f86f411aad95c253eb0ba41cfda1007374941625f1 (height=1259647) closed 0 channels
lnd: 2018-01-20 10:20:43.818 [INF] CRTR: Block 00000000000004ca207ecf32e489da15f75e60c036515e9cc14360e2a97b700b (height=1259648) closed 0 channels
lnd: 2018-01-20 10:20:43.818 [INF] CRTR: Block 000000000000042a666c0afc139bd9a03ee124cad6f8a25ac458b645b780b7c2 (height=1259649) closed 0 channels
lnd: 2018-01-20 10:20:43.818 [INF] CRTR: Block 0000000000000771056a88514aef93c5d9d858c2107b6e02296f8fcf8bb7edb9 (height=1259650) closed 0 channels
lnd: 2018-01-20 10:20:43.819 [INF] CRTR: Block 00000000000c07d04b5a23bc493dc9a273a53a3d88a8927792075646878fae4c (height=1259651) closed 0 channels
lnd: 2018-01-20 10:20:43.820 [INF] CRTR: Block 0000000000000545cabcfd185f4ca3f0759c4f22ec41252344123ff9e610f76b (height=1259652) closed 0 channels
lnd: 2018-01-20 10:20:43.821 [INF] CRTR: Block 000000000000070397deb615e3ad1cdcb9cca31538491179b8507ed587957bcc (height=1259653) closed 0 channels
lnd: 2018-01-20 10:20:43.821 [INF] CRTR: Block 000000000000019157d2d9e0e8051ee40d48a361304c748e0075505fb57eb464 (height=1259654) closed 0 channels
lnd: 2018-01-20 10:20:43.822 [INF] CRTR: Block 000000000000008eae05638971f9409b96215cb363fd71a2534d8e5407f7d964 (height=1259655) closed 0 channels
lnd: 2018-01-20 10:20:43.822 [INF] CRTR: Block 000000003174b04c52212ab1aa00268dab22c2850cf6b47b61cdba86155c1219 (height=1259656) closed 0 channels
lnd: 2018-01-20 10:20:43.823 [INF] CRTR: Block 0000000000000019c299dc1a1b03d2e30ccdd3f58fbf41a6b2f465cf2aed9a14 (height=1259657) closed 0 channels
lnd: 2018-01-20 10:20:43.823 [INF] CRTR: Block 000000005f3fd13c19d142e0a11937025843f65fcfc3e0ad6978b46d5b5dbdd0 (height=1259658) closed 0 channels
lnd: 2018-01-20 10:20:43.824 [INF] CRTR: Block 000000002588946d5c4f94f61387f34f6c9d44f66b73b236d5cab950f00216e0 (height=1259659) closed 0 channels
lnd: 2018-01-20 10:20:43.824 [INF] CRTR: Block 000000000000028368a4d1fb8385e0430db00e038db38ef3ea11b5af9d23e7d8 (height=1259660) closed 0 channels
lnd: 2018-01-20 10:20:43.825 [INF] CRTR: Block 00000000000002654b99e3abf6cc5b27bf5230696d270d5c2ee324f036d30dbb (height=1259661) closed 0 channels
lnd: 2018-01-20 10:20:43.825 [INF] CRTR: Block 0000000084ac0793c752843cf7a948a41b402ecfa3138d9d6108ebf45147adbb (height=1259662) closed 0 channels
lnd: 2018-01-20 10:20:43.825 [INF] CRTR: Block 000000000000019f7617e73d7411ed2f8b4772d6b2fb09ae6e8d9804952af35b (height=1259663) closed 0 channels
lnd: 2018-01-20 10:20:43.826 [INF] CRTR: Block 000000000000003852964e4807b213f2b9b46be7ca81f6f443d04f439aec99fc (height=1259664) closed 0 channels
lnd: 2018-01-20 10:20:43.826 [INF] CRTR: Block 00000000000004199898804cac390ad5b5429a8834afe7a79d733d8eaf46f6ae (height=1259665) closed 0 channels
lnd: 2018-01-20 10:20:43.827 [INF] CRTR: Block 0000000000000201773405ef4ded9c2ef3044961369a3c199a238ec80dffe96c (height=1259666) closed 0 channels
lnd: 2018-01-20 10:20:43.827 [INF] CRTR: Block 00000000b2f64790465888bfec927ffca8991d0d367523e6d20ec59b3d41c71d (height=1259667) closed 0 channels
lnd: 2018-01-20 10:20:43.828 [INF] CRTR: Block 00000000f8b049225e13f0b72383eca60f57598c65bef9e88005f61a61776aff (height=1259668) closed 0 channels
lnd: 2018-01-20 10:20:43.828 [INF] CRTR: Block 000000008c93ab8bb4f385723ac440381604d46a6dba285a74330945ecc055ef (height=1259669) closed 0 channels
lnd: 2018-01-20 10:20:43.829 [INF] CRTR: Block 00000000a8d10ad6b41eae05bb412fdde8e820e6a507e1e98e8c5860c3a7a17f (height=1259670) closed 0 channels
lnd: 2018-01-20 10:20:43.829 [INF] CRTR: Block 00000000fa55a524a07ee69b0c0a7db63fbbc1b44b7fe7d5aa8053f759ee8e34 (height=1259671) closed 0 channels
lnd: 2018-01-20 10:20:43.830 [INF] CRTR: Block 000000005e6947e823eca6caf66d98bc52b68f214522e76e3bed2491d51427c7 (height=1259672) closed 0 channels
lnd: 2018-01-20 10:20:43.830 [INF] CRTR: Block 000000000014f5cd7782309b2b861928bafbc0847293098a50011d5cab51d60e (height=1259673) closed 0 channels
lnd: 2018-01-20 10:20:43.830 [INF] CRTR: Block 00000000000005ee9bee757af19b4ad555cc4283e86209cc1744acb88671badc (height=1259674) closed 0 channels
lnd: 2018-01-20 10:20:43.831 [INF] CRTR: Block 00000000000000e2ad1bf91593d50fe815f959f9bfc3a17506a7824b44d2e50d (height=1259675) closed 0 channels
lnd: 2018-01-20 10:20:43.831 [INF] CRTR: Block 000000000000073bbba09cfb8ed2321c48a8128975012a9f0a78e41b1a4c1747 (height=1259676) closed 0 channels
lnd: 2018-01-20 10:20:43.832 [INF] CRTR: Block 00000000000e5c5afe97f69113f3ddb8549747b42241cb1534ee99c73755001d (height=1259677) closed 0 channels
lnd: 2018-01-20 10:20:43.832 [INF] CRTR: Block 000000000000018f4b773e75aa7b6af5d871665a16e03fe51fa698f7886fbc03 (height=1259678) closed 0 channels
lnd: 2018-01-20 10:20:43.833 [INF] CRTR: Block 00000000000003eabecc6c21db71c3e748d55fd611cab4ded80d1048b196131f (height=1259679) closed 0 channels
lnd: 2018-01-20 10:20:43.833 [INF] CRTR: Block 0000000007e6f39fbaf02011042ccc82d86375c1bbddafe37fb326bd208a7912 (height=1259680) closed 0 channels
lnd: 2018-01-20 10:20:43.834 [INF] CRTR: Block 000000005b790641c20b247ad401c7754483c60e214555802c744e098f1f3eca (height=1259681) closed 0 channels
lnd: 2018-01-20 10:20:43.834 [INF] CRTR: Block 000000000000024aa5c8ab682d2b08d1820b1da1be660bdab2f50b1a30d12998 (height=1259682) closed 0 channels
lnd: 2018-01-20 10:20:43.835 [INF] CRTR: Block 000000000013fe7b214f647baae2c606c89a33e537a849ad329578eaad6d1e9e (height=1259683) closed 0 channels
lnd: 2018-01-20 10:20:43.835 [INF] CRTR: Block 00000000000000b925e6b4450005f03502ac629aebf8ff6c484f0742b1ba8d30 (height=1259684) closed 0 channels
lnd: 2018-01-20 10:20:43.836 [INF] CRTR: Block 000000003c236a56b38b81bec6ce1aba3dba2afdf6325f35e7cd162ca2aebe7c (height=1259685) closed 0 channels
lnd: 2018-01-20 10:20:43.836 [INF] CRTR: Block 00000000c92c1a317ce549aaa25922a75bcb97f4e270cb02b9140f1920576f06 (height=1259686) closed 0 channels 2018-01-20 10:20:43.836 [INF] CRTR: Graph pruning complete: 0 channels we're closed since height 1259618
lnd: 2018-01-20 10:20:43.836 [INF] SRVR: Initializing peer network boostrappers!
lnd: 2018-01-20 10:20:43.837 [INF] SRVR: Creating DNS peer boostrapper with seeds: [[nodes.lightning.directory soa.nodes.lightning.directory]]
lnd: 2018-01-20 10:20:43.837 [INF] CMGR: Server listening on [::]:9735 2018-01-20 10:20:43.837 [INF] DISC: Attempting to bootstrap with: Authenticated Channel Graph
lnd Error: panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x17b55b2] goroutine 271 [running]:
lnd Error: github.com/lightningnetwork/lnd/discovery.createChanAnnouncement(0x0, 0xc4305bad20, 0x0, 0x0, 0x0, 0x0, 0x0) /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/discovery/utils.go:26 +0x72 github.com/lightningnetwork/lnd/discovery.(*AuthenticatedGossiper).processRejectedEdge(0xc4202b8a80, 0xc420082680, 0x0, 0x2, 0x2, 0x1, 0xc420281501, 0x10422fb) /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/discovery/gossiper.go:1127 +0xc0 github.com/lightningnetwork/lnd/discovery.(*AuthenticatedGossiper).processNetworkAnnouncement(0xc4202b8a80, 0xc420217d70, 0xc420082680, 0x1489647, 0xc420168e00) /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/discovery/gossiper.go:1331 +0x58fa github.com/lightningnetwork/lnd/discovery.(*AuthenticatedGossiper).networkHandler.func1(0xc42029e7b0, 0xc420217d70, 0xc4202b8a80, 0xc43069a5e0) /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/discovery/gossiper.go:841 +0x91 created by github.com/lightningnetwork/lnd/discovery.(*AuthenticatedGossiper).networkHandler /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/discovery/gossiper.go:857 +0x68c
```

**Comment by Roasbeef** [comment]
This was fixed within `lnd`, and has now been packaged in the latest version of the app.
