### ISSUE TITLE
Auto update not being triggered

### ISSUE THREAD

**Issue by tanx** [lightninglabs/lightning-app#367]

**Comment by valentinewallace** [comment]
@tanx could you tell me what steps you took? Auto-update is working for me from the master branch. 

steps i took:
* manually created this release on my own fork: https://github.com/valentinewallace/lightning-app/releases/tag/v0.2.0-prealpha.7
* locally built the app with a lower version number (specified in package.json) (also specified my personal fork as the repository) 
* when I run the locally-built package, it asks me if i want to install the update 

I think there could be a problem with the way we're building/deploying? it only works if the tag is correct afaict

**Comment by valentinewallace** [comment]
Auto update works if you manually tag the github release with the correct version. working on making this automatic through electron builder

**Comment by tanx** [comment]
It seems the update is not triggered on may mac due to a missing signature

```
Error: Could not get code signature for running application
    at Server.server.listen (/Users/tanx/Projects/lightninglabs/lightning-app/dist/mac/Lightning.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:89:28)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:105:13)
    at Server.emit (events.js:207:7)
    at emitListeningNT (net.js:1346:10)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Error: Error: Could not get code signature for running application
    at Server.server.listen (/Users/tanx/Projects/lightninglabs/lightning-app/dist/mac/Lightning.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:89:28)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:105:13)
    at Server.emit (events.js:207:7)
    at emitListeningNT (net.js:1346:10)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
I'll set up code signing on my mac: https://github.com/lightninglabs/lightning-app/issues/364

**Comment by tanx** [comment]
Putting this back to the Backlog since there's this won't work until we have code signing working.

**Comment by tanx** [comment]
Got this working for mac and @valentinewallace tested this on Linux.
