### ISSUE TITLE
panic after unknown message received.

### ISSUE THREAD

**Issue by bjd** [lightninglabs/lightning-app#53]
I had a bunch of 'unknown message received' errors followed by go panic. 
A restart was required to get the wallet app going again.

```
lnd: 2017-10-16 22:16:04.870 [ERR] PEER: unknown message received from peer xxx.xxx.xxx.xxx:9735
lnd: 2017-10-16 22:16:04.988 [ERR] PEER: unknown message received from peer xxx.xxx.xxx.xxx:9735
lnd Error: panic: runtime error: index out of range goroutine 1414 [running]:
github.com/lightningnetwork/lnd/lnwallet.genHtlcSigValidationJobs(0xc4210c8320, 0xc4208bafc0, 0xc42000c180, 0x1, 0x1, 0xc420189268, 0xc4201892b8, 0x1000000, 0xc4202e2e00, 0x20) /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:2631 +0x8a0
github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).ReceiveNewCommitment(0xc4212342c0, 0xc420c9ac90, 0xc42000c180, 0x1, 0x1, 0x0, 0x0) /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:2723 +0x5cf
github.com/lightningnetwork/lnd/htlcswitch.(*channelLink).handleUpstreamMsg(0xc421602000, 0x1322660, 0xc42107c980) /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/htlcswitch/link.go:776 +0xc8a
github.com/lightningnetwork/lnd/htlcswitch.(*channelLink).htlcManager(0xc421602000) /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/htlcswitch/link.go:466 +0xcb5
created by
github.com/lightningnetwork/lnd/htlcswitch.(*channelLink).Start /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/htlcswitch/link.go:272 +0x116
```

--edit--
Shortly after restart it happened again, 7 unknown messages from the same peer followed by the same panic.

**Comment by Roasbeef** [comment]
Will be addressed after I fix https://github.com/lightningnetwork/lnd/issues/137

**Comment by Roasbeef** [comment]
`v0.1.3` packages a version of `lnd` with the above fix. Closing.
