### ISSUE TITLE
Lightining pre alpha.24 doesn't start.

### ISSUE THREAD

**Issue by bitcoinuser** [lightninglabs/lightning-app#566]
leonardo@leonardo-Aspire-V5-471:~/Área de Trabalho$ ./Lightning-linux-x86_64v0.2.0-prealpha.24.AppImage

 ___       ________       ________  ________  ________
|\  \     |\   ___  \    |\   __  \|\   __  \|\   __  \
\ \  \    \ \  \\ \  \   \ \  \|\  \ \  \|\  \ \  \|\  \
 \ \  \    \ \  \\ \  \   \ \   __  \ \   ____\ \   ____\
  \ \  \____\ \  \\ \  \   \ \  \ \  \ \  \___|\ \  \___|
   \ \_______\ \__\\ \__\   \ \__\ \__\ \__\    \ \__\
    \|_______|\|__| \|__|    \|__|\|__|\|__|     \|__|

[10:21:42.733] [info] Using lnd in path /tmp/.mount_LightnOikgpt/app/resources/assets/bin/linux/lnd
Checking for update
[10:21:43.222] [info] lnd: 2018-08-28 10:21:43.200 [WRN] LTND: open /home/leonardo/.config/lightning-app/lnd/lnd.conf: no such file or directory
2018-08-28 10:21:43.217 [INF] LTND: Version 0.4.2-beta commit=625b210f441ece841c76b81377dd96e8d09aba8e
2018-08-28 10:21:43.217 [INF] LTND: Active chain: Bitcoin (network=testnet)
2018-08-28 10:21:43.218 [INF] CHDB: Checking for schema update: latest_version=5, db_version=5

[10:21:43.278] [info] lnd: 2018-08-28 10:21:43.277 [INF] RPCS: password RPC server listening on 127.0.0.1:10009

[10:21:43.287] [info] lnd: 2018-08-28 10:21:43.287 [INF] RPCS: password gRPC proxy started at 127.0.0.1:8080

[10:21:43.288] [info] lnd: 2018-08-28 10:21:43.288 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create a wallet, `lncli unlock` to unlock an existing wallet, or `lncli changepassword` to change the password of an existing wallet and unlock it.

[10:21:43.687] [info] Loaded initial state
[10:21:44.267] [info] GRPC unlockerReady
Update for version 0.2.0-prealpha.24 is not available (latest version: 0.2.0-prealpha.24, downgrade is disallowed).
[10:21:49.227] [info] lnd: 2018-08-28 10:21:49.227 [INF] LNWL: Opened wallet

[10:21:49.390] [info] lnd: 2018-08-28 10:21:49.390 [INF] LTND: Primary chain is set to: bitcoin

[10:21:49.574] [info] lnd: 2018-08-28 10:21:49.574 [INF] BTCN: Loaded 1761 addresses from file '/home/leonardo/.config/lightning-app/lnd/data/chain/bitcoin/testnet/peers.json'

[10:21:49.575] [info] lnd: 2018-08-28 10:21:49.575 [INF] BTCN: Waiting for block headers to sync, then will start cfheaders sync...

[10:21:49.576] [info] lnd: 2018-08-28 10:21:49.575 [INF] BTCN: Starting cfheaders sync at block_height=1410519, hash=00000000000000a4b90e4eb69734fe64dd0265739e868d752212528cf915d6be
2018-08-28 10:21:49.575 [INF] BTCN: Starting cfheaders sync for filter_type=0
2018-08-28 10:21:49.576 [WRN] BTCN: Unable to fetch set of candidate checkpoints, trying again...

[10:21:49.578] [info] lnd: 2018-08-28 10:21:49.578 [INF] CMGR: DNS discovery failed on seed x49.testnet-seed.bitcoin.jonasschnelli.ch: lookup x49.testnet-seed.bitcoin.jonasschnelli.ch on 127.0.0.53:53: no such host

[10:21:49.595] [info] lnd: 2018-08-28 10:21:49.595 [INF] CMGR: DNS discovery failed on seed x49.seed.tbtc.petertodd.org: lookup x49.seed.tbtc.petertodd.org on 127.0.0.53:53: no such host

[10:21:49.759] [info] lnd: 2018-08-28 10:21:49.759 [INF] CMGR: 3 addresses found from DNS seed testnet-seed.bluematt.me

[10:21:50.067] [info] lnd: 2018-08-28 10:21:50.067 [INF] BTCN: New valid peer 104.155.159.141:18333 (outbound) (/btcwire:0.5.0/btcd:0.12.0/)

[10:21:50.068] [info] lnd: 2018-08-28 10:21:50.068 [INF] BTCN: Syncing to block height 1410520 from peer 104.155.159.141:18333

[10:21:50.068] [info] lnd: 2018-08-28 10:21:50.068 [INF] BTCN: Fetching set of headers from tip (height=1410519) from peer 104.155.159.141:18333

[10:21:50.623] [info] lnd: 2018-08-28 10:21:50.623 [INF] LNWL: The wallet has been unlocked without a time limit
2018-08-28 10:21:50.623 [INF] LTND: LightningWallet opened

[10:21:50.761] [info] lnd: 2018-08-28 10:21:50.760 [INF] LNWL: Started rescan from block 000000000000003c4babb65f187f7cf32025fd1549e1fc02dd3a27daf4e1a8fd (height 1409594) for 2 addresses

[10:21:50.786] [info] lnd: 2018-08-28 10:21:50.785 [INF] HSWC: Restoring in-memory circuit state from disk

[10:21:50.830] [info] lnd: 2018-08-28 10:21:50.830 [INF] HSWC: Payment circuits loaded: num_pending=0, num_open=0

[10:21:50.910] [info] lnd: 2018-08-28 10:21:50.908 [INF] RPCS: RPC server listening on 127.0.0.1:10009
2018-08-28 10:21:50.909 [INF] LTND: Waiting for chain backend to finish sync, start_height=1410520
2018-08-28 10:21:50.909 [INF] RPCS: gRPC proxy started at 127.0.0.1:8080

[10:21:53.315] [info] lnd: 2018-08-28 10:21:53.315 [INF] BTCN: Fetching set of checkpointed cfheaders filters from height=1409821, hash=8f044d023be796ae290bd323be655d437f98ad3eebd36d45e6349d7bdd0eeb7b
2018-08-28 10:21:53.315 [INF] BTCN: Starting to query for cfheaders from checkpoint_interval=1409

[10:21:53.318] [info] lnd: 2018-08-28 10:21:53.315 [INF] BTCN: Attempting to query for 1 cfheader batches

[10:21:53.782] [error] lnd Error: panic: runtime error: slice bounds out of range

goroutine 98 [running]:
github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino.(*blockManager).getCheckpointedCFHeaders.func1(0xc420348140, 0x11ac720, 0xc4405ee990, 0x11ac4e0, 0xc430573020, 0x0)
	/home/travis/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino/blockmanager.go:868 +0xb35
github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino.(*ChainService).queryBatch(0xc42044e500, 0xc4207d4000, 0x1, 0x582, 0xc4208cbe40, 0xc4202a00c0, 0x0, 0x0, 0x0)
	/home/travis/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino/query.go:392 +0xa3c

[10:21:53.783] [error] lnd Error: github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino.(*blockManager).getCheckpointedCFHeaders(0xc4202be160, 0xc4405e0000, 0x582, 0x582, 0xc4204600b8, 0x500)
	/home/travis/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino/blockmanager.go:776 +0x8d2
github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino.(*blockManager).cfHandler.func2(0xc42091a910, 0xc4202be160, 0x1585d7, 0xc4208e9640, 0xc4204a3e00, 0x1104428)
	/home/travis/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino/blockmanager.go:500 +0x3b6
created by github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino.(*blockManager).cfHandler
	/home/travis/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino/blockmanager.go:440 +0x402

[10:21:54.234] [info] GRPC unlockerClosed

**Comment by tanx** [comment]
> [10:21:42.733] [info] Using lnd in path /tmp/.mount_LightnOikgpt/app/resources/assets/bin/linux/lnd

Looks like your not running the `prealpha.24` rebuilt binary. If you're using the lnd in your path you need to update lnd to the current master.
