### ISSUE TITLE
Syncing to chain forever

### ISSUE THREAD

**Issue by bitcoinuser** [lightninglabs/lightning-app#658]
[12:40:06.940] [info] Syncing to chain ... block height: 1412995
[12:40:07.437] [info] lnd: 2018-09-11 12:40:07.436 [INF] BTCN: Verified 14000 filter headers in the last 11.82s (height 697001, 2016-02-13 05:06:01 -0200 -02)

[12:40:07.447] [error] lnd Error: panic: couldn't write cfheaders msg: attempt to write cfheaders out of order

goroutine 3822 [running]:
github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino.(*blockManager).getCheckpointedCFHeaders.func1(0xc420194460, 0x11b8240, 0xc42254f0b0, 0x11b8000, 0xc421133bc0, 0x501)
	/home/travis/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino/blockmanager.go:872 +0xb2d
github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino.(*ChainService).queryBatch(0xc42008c500, 0xc420c4c000, 0x584, 0x584, 0xc42091be30, 0xc420370960, 0x0
[12:40:07.451] [error] lnd Error: , 0x0, 0x0)
	/home/travis/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino/query.go:422 +0xa85
github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino.(*blockManager).getCheckpointedCFHeaders(0xc4202d62c0, 0xc420c3a000, 0x584, 0x584, 0xc42000e0c8, 0x500)
	/home/travis/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino/blockmanager.go:775 +0x8d7
github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino.(*blockManager).cfHandler.func2(0xc420340f80, 0xc4202d62c0, 0x158f82, 0xc421542420, 0x11b7300, 0x110eae0)
	/home/travis/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino/blockmanager.go:501 +0x3c5
created by github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino.(*blockManager).cfHandler
	/home/travis/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino/blockmanager.go:441 +0x407

[12:40:07.465] [info] Transactions update: [object Object]
[12:40:07.466] [info] Invoices update: [object Object]
[12:40:07.947] [error] Getting channel balance failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[12:40:07.953] [error] Getting wallet balance failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[12:40:07.954] [error] Getting node info failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[12:40:10.453] [error] Getting node info failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[12:40:10.456] [error] Getting channel balance failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[12:40:10.458] [error] Getting wallet balance failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[12:40:12.706] [error] Getting channel balance failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[12:40:12.708] [error] Getting wallet balance failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[12:40:12.710] [error] Getting node info failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[12:40:17.350] [error] Getting node info failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[12:40:17.353] [error] Getting channel balance failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[12:40:17.355] [error] Getting wallet balance failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[12:40:23.581] [error] Getting channel balance failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[12:40:23.583] [error] Getting wallet balance failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[12:40:23.586] [error] Getting node info failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[12:40:33.923] [error] Getting node info failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[12:40:33.925] [error] Getting channel balance failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[12:40:33.927] [error] Getting wallet balance failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[12:40:49.954] [error] Getting channel balance failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[12:40:49.957] [error] Getting wallet balance failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[12:40:49.959] [error] Getting node info failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[12:41:15.361] [error] Getting node info failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[12:41:15.363] [error] Getting channel balance failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[12:41:15.365] [error] Getting wallet balance failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[12:41:53.883] [error] Getting channel balance failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[12:41:53.886] [error] Getting wallet balance failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[12:41:53.888] [error] Getting node info failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[12:43:07.619] [error] Getting node info failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[12:43:07.623] [error] Getting channel balance failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[12:43:07.625] [error] Getting wallet balance failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[12:44:38.432] [error] Getting channel balance failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[12:44:38.434] [error] Getting wallet balance failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[12:44:38.436] [error] Getting node info failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[12:46:01.662] [info] Saved state
[12:46:59.039] [error] Getting node info failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[12:46:59.042] [error] Getting channel balance failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[12:46:59.044] [error] Getting wallet balance failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[12:49:00.824] [error] Getting channel balance failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[12:49:00.827] [error] Getting wallet balance failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[12:49:00.829] [error] Getting node info failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[12:51:00.633] [error] Getting node info failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[12:51:00.636] [error] Getting channel balance failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[12:51:00.638] [error] Getting wallet balance failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }

**Comment by bitcoinuser** [comment]
Restarted and now never finish syncronizing:

[13:03:16.255] [info] Syncing to chain ... block height: 1412996
[13:03:18.255] [info] Syncing to chain ... block height: 1412996
[13:03:20.256] [info] Syncing to chain ... block height: 1412996
[13:03:22.255] [info] Syncing to chain ... block height: 1412996
[13:03:24.157] [info] lnd: 2018-09-11 13:03:24.156 [INF] BTCN: Verified 16000 filter headers in the last 10.22s (height 1391001, 2018-08-22 14:48:04 -0300 -03)

[13:03:24.256] [info] Syncing to chain ... block height: 1412996
[13:03:26.257] [info] Syncing to chain ... block height: 1412996
[13:03:28.256] [info] Syncing to chain ... block height: 1412996
[13:03:30.255] [info] Syncing to chain ... block height: 1412996
[13:03:32.261] [info] Syncing to chain ... block height: 1412996
[13:03:34.256] [info] Syncing to chain ... block height: 1412996
[13:03:34.513] [info] lnd: 2018-09-11 13:03:34.512 [INF] BTCN: Verified 16000 filter headers in the last 10.35s (height 1407001, 2018-08-23 04:44:20 -0300 -03)

[13:03:36.253] [info] Syncing to chain ... block height: 1412996
[13:03:38.251] [info] Syncing to chain ... block height: 1412996
[13:03:39.971] [info] lnd: 2018-09-11 13:03:39.970 [INF] BTCN: Fully caught up with cfheaders at height 1412995, waiting at tip for new blocks

[13:03:39.974] [info] lnd: 2018-09-11 13:03:39.971 [INF] BTCN: Attempting to fetch set of un-checkpointed filters at height=1412996, hash=000000004c3604d758cba41c30c1f2be2ffa3e730a3017ded08078dc422a614e

[13:03:40.256] [info] Syncing to chain ... block height: 1412996
[13:03:42.256] [info] Syncing to chain ... block height: 1412996
[13:03:44.258] [info] Syncing to chain ... block height: 1412996
[13:03:46.256] [info] Syncing to chain ... block height: 1412996
[13:03:48.256] [info] Syncing to chain ... block height: 1412996
[13:03:50.256] [info] Syncing to chain ... block height: 1412996
[13:03:52.256] [info] Syncing to chain ... block height: 1412996
[13:03:54.256] [info] Syncing to chain ... block height: 1412996
[13:03:56.257] [info] Syncing to chain ... block height: 1412996
[13:03:58.256] [info] Syncing to chain ... block height: 1412996
[13:04:00.256] [info] Syncing to chain ... block height: 1412996
[13:04:02.257] [info] Syncing to chain ... block height: 1412996
[13:04:04.253] [info] Syncing to chain ... block height: 1412996
[13:04:06.257] [info] Syncing to chain ... block height: 1412996
[13:04:08.257] [info] Syncing to chain ... block height: 1412996
[13:04:10.255] [info] Syncing to chain ... block height: 1412996
[13:04:12.254] [info] Syncing to chain ... block height: 1412996
[13:04:14.257] [info] Syncing to chain ... block height: 1412996
[13:04:16.257] [info] Syncing to chain ... block height: 1412996
[13:04:18.257] [info] Syncing to chain ... block height: 1412996

**Comment by bitcoinuser** [comment]
Deposited bitcoin but the bitcoins never show on lightning app. Nothing happens.

**Comment by Roasbeef** [comment]
That second post looks fine, that's it syncing up to the network itself. Confirmations on testent right now may take a few blocks, as not all the active miners are mining segwit transactions.

**Comment by Roasbeef** [comment]
For that other paste, the wallet is catching up in the background there but it isn't reflected in the logs atm. We have a fix for that in an unmerged neutrino PR, that should be rolled out onto the app within the next week or so.

**Comment by bitcoinuser** [comment]
Opened the app again and now I can't generate an address:

![captura de tela de 2018-09-12 08-40-34](https://user-images.githubusercontent.com/1178856/45422782-a58a6f80-b667-11e8-9a1a-a625ac876d60.png)

Logs:

:39:30.176] [info] Syncing to chain ... block height: 1413139
[08:39:32.185] [info] Syncing to chain ... block height: 1413139
[08:39:34.181] [info] Syncing to chain ... block height: 1413139
[08:39:36.178] [info] Syncing to chain ... block height: 1413139
[08:39:38.177] [info] Syncing to chain ... block height: 1413139
[08:39:40.185] [info] Syncing to chain ... block height: 1413139
[08:39:42.173] [info] Syncing to chain ... block height: 1413139
[08:39:44.180] [info] Syncing to chain ... block height: 1413139
[08:39:46.176] [info] Syncing to chain ... block height: 1413139
[08:39:48.176] [info] Syncing to chain ... block height: 1413139
[08:39:50.173] [info] Syncing to chain ... block height: 1413139
[08:39:51.185] [info] Syncing to chain ... block height: 1413139
[08:39:52.195] [info] Syncing to chain ... block height: 1413139
[08:39:53.206] [info] Syncing to chain ... block height: 1413139
[08:39:54.219] [info] Syncing to chain ... block height: 1413139
[08:39:55.227] [info] Syncing to chain ... block height: 1413139
[08:39:56.237] [info] Syncing to chain ... block height: 1413139
[08:39:56.828] [info] lnd: 2018-09-12 08:39:56.827 [INF] BTCN: Processed 96 blocks in the last 1m41.4s (height 1413140, 2018-09-12 08:39:48 -0300 -03)

[08:39:56.935] [info] lnd: 2018-09-12 08:39:56.934 [INF] BTCN: Attempting to fetch set of un-checkpointed filters at height=1413140, hash=0000000002d3b0b87bfb5d95aeb33d6c32780afbdac8a784e2ceff2329ff1a4c

[08:39:57.223] [info] lnd: 2018-09-12 08:39:57.223 [INF] BTCN: Verified 95 filter headers in the last 1m15.61s (height 1413140, 2018-09-12 08:39:48 -0300 -03)

[08:39:57.248] [info] Syncing to chain ... block height: 1413140
[08:39:58.256] [info] Syncing to chain ... block height: 1413140
[08:39:59.270] [info] Syncing to chain ... block height: 1413140
[08:40:00.278] [info] Syncing to chain ... block height: 1413140
[08:40:01.286] [info] Syncing to chain ... block height: 1413140
[08:40:02.296] [info] Syncing to chain ... block height: 1413140
[08:40:03.306] [info] Syncing to chain ... block height: 1413140
[08:40:04.316] [info] Syncing to chain ... block height: 1413140
[08:40:05.325] [info] Syncing to chain ... block height: 1413140
[08:40:06.337] [info] Syncing to chain ... block height: 1413140
[08:40:07.348] [info] Syncing to chain ... block height: 1413140
[08:40:08.359] [info] Syncing to chain ... block height: 1413140
[08:40:09.366] [info] Syncing to chain ... block height: 1413140
[08:40:10.375] [info] Syncing to chain ... block height: 1413140
[08:40:11.385] [info] Syncing to chain ... block height: 1413140

**Comment by bitcoinuser** [comment]
Syncing to chain forever.

**Comment by bitcoinuser** [comment]
leonardo@leonardo-Aspire-V5-471:~/Área de Trabalho$ ./Lightning-linux-x86_64v0.2.1-alpha.AppImage

 ___       ________       ________  ________  ________
|\  \     |\   ___  \    |\   __  \|\   __  \|\   __  \
\ \  \    \ \  \\ \  \   \ \  \|\  \ \  \|\  \ \  \|\  \
 \ \  \    \ \  \\ \  \   \ \   __  \ \   ____\ \   ____\
  \ \  \____\ \  \\ \  \   \ \  \ \  \ \  \___|\ \  \___|
   \ \_______\ \__\\ \__\   \ \__\ \__\ \__\    \ \__\
    \|_______|\|__| \|__|    \|__|\|__|\|__|     \|__|



[08:48:44.697] [info] Using lnd in path /tmp/.mount_Lightnzw6YC9/app/resources/assets/bin/linux/lnd
Checking for update
[08:48:45.215] [info] lnd: 2018-09-12 08:48:45.211 [WRN] LTND: open /home/leonardo/.config/lightning-app/lnd/lnd.conf: no such file or directory

[08:48:45.216] [info] lnd: 2018-09-12 08:48:45.215 [INF] LTND: Version 0.5.0-beta commit=51d43be1f369c7ec5ae8bc3bb282a45c6a0776ea
2018-09-12 08:48:45.215 [INF] LTND: Active chain: Bitcoin (network=testnet)

[08:48:45.216] [info] lnd: 2018-09-12 08:48:45.216 [INF] CHDB: Checking for schema update: latest_version=6, db_version=6

[08:48:45.250] [info] lnd: 2018-09-12 08:48:45.249 [INF] RPCS: password RPC server listening on 127.0.0.1:10006

[08:48:45.252] [info] lnd: 2018-09-12 08:48:45.251 [INF] RPCS: password gRPC proxy started at 127.0.0.1:8086
2018-09-12 08:48:45.251 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create a wallet, `lncli unlock` to unlock an existing wallet, or `lncli changepassword` to change the password of an existing wallet and unlock it.

[08:48:45.638] [info] Loaded initial state
[08:48:46.204] [info] GRPC unlockerReady
Update for version 0.2.1-alpha is not available (latest version: 0.2.1-alpha, downgrade is disallowed).
[08:48:51.342] [info] lnd: 2018-09-12 08:48:51.341 [INF] LNWL: Opened wallet

[08:48:51.503] [info] lnd: 2018-09-12 08:48:51.503 [INF] LTND: Primary chain is set to: bitcoin

[08:48:51.723] [info] lnd: 2018-09-12 08:48:51.721 [INF] LTND: Using testnet API fee estimator!

[08:48:51.843] [info] lnd: 2018-09-12 08:48:51.842 [INF] BTCN: Loaded 1004 addresses from file '/home/leonardo/.config/lightning-app/lnd/data/chain/bitcoin/testnet/peers.json'

[08:48:51.845] [info] lnd: 2018-09-12 08:48:51.843 [INF] BTCN: Waiting for block headers to sync, then will start cfheaders sync...
2018-09-12 08:48:51.843 [INF] BTCN: Starting cfheaders sync at block_height=1413140, hash=0000000002d3b0b87bfb5d95aeb33d6c32780afbdac8a784e2ceff2329ff1a4c
2018-09-12 08:48:51.843 [INF] BTCN: Starting cfheaders sync for filter_type=0
2018-09-12 08:48:51.843 [WRN] BTCN: Unable to fetch set of candidate checkpoints, trying again...

[08:48:52.006] [info] lnd: 2018-09-12 08:48:52.006 [INF] CMGR: DNS discovery failed on seed x49.seed.tbtc.petertodd.org: lookup x49.seed.tbtc.petertodd.org on 127.0.0.53:53: no such host

[08:48:52.023] [info] lnd: 2018-09-12 08:48:52.023 [INF] CMGR: DNS discovery failed on seed x49.testnet-seed.bitcoin.jonasschnelli.ch: lookup x49.testnet-seed.bitcoin.jonasschnelli.ch on 127.0.0.53:53: no such host

[08:48:52.140] [info] lnd: 2018-09-12 08:48:52.139 [INF] CMGR: 3 addresses found from DNS seed testnet-seed.bluematt.me

[08:48:52.199] [info] lnd: 2018-09-12 08:48:52.198 [INF] CMGR: 1 addresses found from DNS seed testnet-seed.bitcoin.schildbach.de

[08:48:52.396] [info] lnd: 2018-09-12 08:48:52.396 [INF] BTCN: New valid peer 104.155.159.141:18333 (outbound) (/btcwire:0.5.0/btcd:0.12.0/)

[08:48:52.397] [info] lnd: 2018-09-12 08:48:52.397 [INF] BTCN: Syncing to block height 1413141 from peer 104.155.159.141:18333
2018-09-12 08:48:52.397 [INF] BTCN: Fetching set of headers from tip (height=1413140) from peer 104.155.159.141:18333

[08:48:52.820] [info] lnd: 2018-09-12 08:48:52.819 [INF] LNWL: The wallet has been unlocked without a time limit

[08:48:52.820] [info] lnd: 2018-09-12 08:48:52.820 [INF] LTND: LightningWallet opened

[08:48:53.021] [info] lnd: 2018-09-12 08:48:53.020 [INF] LNWL: Started rescan from block 0000000000000034ce011a47d8b0d5c857fedc0465ea6c54533b4cb1e26d244d (height 1412999) for 11 addresses

[08:48:53.050] [info] lnd: 2018-09-12 08:48:53.049 [INF] HSWC: Restoring in-memory circuit state from disk

[08:48:53.105] [info] lnd: 2018-09-12 08:48:53.105 [INF] HSWC: Payment circuits loaded: num_pending=0, num_open=0

[08:48:53.217] [info] lnd: 2018-09-12 08:48:53.217 [INF] RPCS: RPC server listening on 127.0.0.1:10006
2018-09-12 08:48:53.217 [INF] RPCS: gRPC proxy started at 127.0.0.1:8086

[08:48:53.218] [info] lnd: 2018-09-12 08:48:53.217 [INF] LTND: Waiting for chain backend to finish sync, start_height=1413141

[08:48:56.346] [info] GRPC unlockerClosed
[08:48:56.352] [info] GRPC lndReady
[08:48:56.368] [info] lnd: 2018-09-12 08:48:56.366 [INF] RPCS: [listchannels] fetched 0 channels from DB

[08:48:56.429] [info] Syncing to chain ... block height: 1413141
[08:48:57.436] [info] Syncing to chain ... block height: 1413141
[08:48:57.844] [info] lnd: 2018-09-12 08:48:57.844 [WRN] BTCN: Unable to fetch set of candidate checkpoints, trying again...

[08:48:58.440] [info] Syncing to chain ... block height: 1413141
[08:48:58.702] [info] Saved state
[08:48:59.346] [error] Getting new wallet address failed { code: 2,
  details: 'Rescan is already done and cannot be updated. It returned error: Couldn\'t retrieve block 0000000062d63cdf765bc27589ddeeae5632a64b57ae9dd380332d64c5c55d67 from network',
  metadata: { _internal_repr: {} } }
[08:49:00.178] [info] Syncing to chain ... block height: 1413141
[08:49:02.180] [info] Syncing to chain ... block height: 1413141
[08:49:03.845] [info] lnd: 2018-09-12 08:49:03.845 [WRN] BTCN: Unable to fetch set of candidate checkpoints, trying again...

[08:49:04.178] [info] Syncing to chain ... block height: 1413141
[08:49:06.178] [info] Syncing to chain ... block height: 1413141
[08:49:08.178] [info] Syncing to chain ... block height: 1413141
[08:49:09.846] [info] lnd: 2018-09-12 08:49:09.845 [WRN] BTCN: Unable to fetch set of candidate checkpoints, trying again...

[08:49:10.177] [info] Syncing to chain ... block height: 1413141
[08:49:12.178] [info] Syncing to chain ... block height: 1413141
[08:49:14.174] [info] Syncing to chain ... block height: 1413141
[08:49:15.198] [info] lnd: 2018-09-12 08:49:15.197 [INF] BTCN: Fetching set of checkpointed cfheaders filters from height=1413140, hash=ebfe08946d87b252dabb634754610822fd3d1dd532f00c94bde860b667f28bed
2018-09-12 08:49:15.198 [INF] BTCN: Starting to query for cfheaders from checkpoint_interval=1413

[08:49:15.199] [info] lnd: 2018-09-12 08:49:15.198 [INF] BTCN: Attempting to query for 0 cfheader batches

[08:49:16.179] [info] Syncing to chain ... block height: 1413141
[08:49:18.183] [info] Syncing to chain ... block height: 1413141
[08:49:18.199] [info] lnd: 2018-09-12 08:49:18.198 [INF] BTCN: Fully caught up with cfheaders at height 1413140, waiting at tip for new blocks

[08:49:18.200] [info] lnd: 2018-09-12 08:49:18.199 [INF] BTCN: Attempting to fetch set of un-checkpointed filters at height=1413141, hash=000000000000001f0087261ba3f5e029153c10e5f7aee29b566ccfccadda4fc3

[08:49:18.790] [info] lnd: 2018-09-12 08:49:18.790 [INF] BTCN: Verified 1 filter header in the last 27.21s (height 1413141, 2018-09-12 08:48:30 -0300 -03)

[08:49:20.180] [info] Syncing to chain ... block height: 1413141
[08:49:22.180] [info] Syncing to chain ... block height: 1413141
[08:49:24.180] [info] Syncing to chain ... block height: 1413141
[08:49:26.180] [info] Syncing to chain ... block height: 1413141
[08:49:28.180] [info] Syncing to chain ... block height: 1413141
[08:49:30.180] [info] Syncing to chain ... block height: 1413141
[08:49:32.181] [info] Syncing to chain ... block height: 1413141
[08:49:34.180] [info] Syncing to chain ... block height: 1413141
[08:49:36.181] [info] Syncing to chain ... block height: 1413141
[08:49:38.181] [info] Syncing to chain ... block height: 1413141
[08:49:40.173] [info] Syncing to chain ... block height: 1413141
[08:49:42.184] [info] Syncing to chain ... block height: 1413141
[08:49:44.180] [info] Syncing to chain ... block height: 1413141
[08:49:46.181] [info] Syncing to chain ... block height: 1413141
[08:49:48.181] [info] Syncing to chain ... block height: 1413141
[08:49:50.194] [info] Syncing to chain ... block height: 1413141
[08:49:52.177] [info] Syncing to chain ... block height: 1413141
[08:49:54.172] [info] Syncing to chain ... block height: 1413141
[08:49:56.178] [info] Syncing to chain ... block height: 1413141
[08:49:58.178] [info] Syncing to chain ... block height: 1413141

**Comment by tanx** [comment]
Potentially related to #646 ?

**Comment by Roasbeef** [comment]
My guess here is the app was restarted mid-sync, if that's done, at times `lnd` doesn't know that it isn't yet "current", so it goes and attempts to fetch the filters from that point on to tip. We have a fix for this on the backend, but if you crank these logs to `debug`, then you'll likely see it fetching the set of filters.

**Comment by tanx** [comment]
Should be fixed in v0.2.4-alpha

**Comment by tanx** [comment]
Reopening since I got stuck again on the syncing screen on initial sync.

**Comment by tanx** [comment]
I'm stuck on this error on initial sync:

```

**Comment by Roasbeef** [comment]
That message seems benign actually? It'll retry.

**Comment by tanx** [comment]
It may have just been a connection issue. Closing this again.
