### ISSUE TITLE
Lightning app version 0.2.5-alpha

### ISSUE THREAD

**Issue by bitcoinuser** [lightninglabs/lightning-app#722]
[18:31:14.665] [info] Using lnd in path /tmp/.mount_LightnjgIqZ3/app/resources/assets/bin/linux/lnd
Checking for update
[18:31:15.526] [info] lnd: 2018-10-08 18:31:15.523 [WRN] LTND: open /home/leonardo/.config/lightning-app/lnd/lnd.conf: no such file or directory

[18:31:15.528] [info] lnd: 2018-10-08 18:31:15.528 [INF] LTND: Version 0.5.0-beta commit=8f2da60dfa994992c1de9a3a7dc0bc4389b39299

[18:31:15.529] [info] lnd: 2018-10-08 18:31:15.528 [INF] LTND: Active chain: Bitcoin (network=testnet)

[18:31:15.530] [info] lnd: 2018-10-08 18:31:15.529 [INF] CHDB: Checking for schema update: latest_version=6, db_version=6

[18:31:15.603] [info] lnd: 2018-10-08 18:31:15.603 [INF] RPCS: password RPC server listening on 127.0.0.1:10006

[18:31:15.606] [info] lnd: 2018-10-08 18:31:15.606 [INF] RPCS: password gRPC proxy started at 127.0.0.1:8086
2018-10-08 18:31:15.606 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create a wallet, `lncli unlock` to unlock an existing wallet, or `lncli changepassword` to change the password of an existing wallet and unlock it.

[18:31:15.991] [info] Loaded initial state
[18:31:16.577] [info] GRPC unlockerReady
Update for version 0.2.5-alpha is not available (latest version: 0.2.5-alpha, downgrade is disallowed).
[18:31:31.793] [info] lnd: 2018-10-08 18:31:31.792 [INF] LNWL: Opened wallet

[18:31:31.981] [info] lnd: 2018-10-08 18:31:31.981 [INF] LTND: Primary chain is set to: bitcoin

[18:31:32.056] [info] lnd: 2018-10-08 18:31:32.056 [INF] LTND: Using testnet API fee estimator!

[18:31:32.073] [info] lnd: 2018-10-08 18:31:32.073 [INF] BTCN: Loaded 1004 addresses from file '/home/leonardo/.config/lightning-app/lnd/data/chain/bitcoin/testnet/peers.json'

[18:31:32.074] [info] lnd: 2018-10-08 18:31:32.074 [INF] BTCN: Waiting for more block headers, then will start cfheaders sync from height 1416000...

[18:31:32.076] [info] lnd: 2018-10-08 18:31:32.076 [INF] BTCN: Starting cfheaders sync from (block_height=1416000, block_hash=00000000f944609b092a2033239358cd3724a9f9fadabfabff1f8f7c477a33a0) to (block_height=1424885, block_hash=0000000000ba8059a53e4746927d0209f9ba8fea8ae330160670c044c545b904)

[18:31:32.078] [info] lnd: 2018-10-08 18:31:32.078 [INF] BTCN: Starting cfheaders sync for filter_type=0

[18:31:32.079] [info] lnd: 2018-10-08 18:31:32.078 [WRN] BTCN: Unable to fetch set of candidate checkpoints, trying again...

[18:31:32.592] [info] lnd: 2018-10-08 18:31:32.592 [INF] BTCN: New valid peer 104.155.159.141:18333 (outbound) (/btcwire:0.5.0/btcd:0.12.0/)

[18:31:32.593] [info] lnd: 2018-10-08 18:31:32.593 [INF] BTCN: Syncing to block height 1433603 from peer 104.155.159.141:18333
2018-10-08 18:31:32.593 [INF] BTCN: Fetching set of headers from tip (height=1424885) from peer 104.155.159.141:18333

[18:31:33.038] [info] lnd: 2018-10-08 18:31:33.038 [INF] CMGR: DNS discovery failed on seed x49.seed.tbtc.petertodd.org: lookup x49.seed.tbtc.petertodd.org on 127.0.0.53:53: no such host

[18:31:33.050] [info] lnd: 2018-10-08 18:31:33.049 [INF] CMGR: DNS discovery failed on seed x49.testnet-seed.bitcoin.jonasschnelli.ch: lookup x49.testnet-seed.bitcoin.jonasschnelli.ch on 127.0.0.53:53: no such host

[18:31:33.116] [info] lnd: 2018-10-08 18:31:33.116 [INF] LNWL: The wallet has been unlocked without a time limit

[18:31:33.116] [info] lnd: 2018-10-08 18:31:33.116 [INF] LTND: LightningWallet opened

[18:31:33.177] [info] lnd: 2018-10-08 18:31:33.177 [INF] CMGR: 1 addresses found from DNS seed testnet-seed.bitcoin.schildbach.de

[18:31:33.309] [info] lnd: 2018-10-08 18:31:33.308 [INF] CMGR: 3 addresses found from DNS seed testnet-seed.bluematt.me

[18:31:33.399] [info] lnd: 2018-10-08 18:31:33.399 [INF] LNWL: Started rescan from block 0000000000000012ad11dbaf6c56aec615f3196a9b971d26043112b49a21053e (height 1413009) for 31 addresses

[18:31:33.428] [info] lnd: 2018-10-08 18:31:33.427 [INF] HSWC: Restoring in-memory circuit state from disk

[18:31:33.484] [info] lnd: 2018-10-08 18:31:33.483 [INF] HSWC: Payment circuits loaded: num_pending=0, num_open=0

[18:31:33.597] [info] lnd: 2018-10-08 18:31:33.595 [INF] LTND: Waiting for chain backend to finish sync, start_height=1424885
2018-10-08 18:31:33.595 [INF] RPCS: RPC server listening on 127.0.0.1:10006
2018-10-08 18:31:33.595 [INF] RPCS: gRPC proxy started at 127.0.0.1:8086

[18:31:34.316] [info] lnd: 2018-10-08 18:31:34.316 [INF] LNWL: Catching up block hashes to height 1413010, this might take a while

[18:31:34.516] [info] lnd: 2018-10-08 18:31:34.516 [INF] LNWL: Done catching up block hashes

[18:31:34.518] [info] lnd: 2018-10-08 18:31:34.516 [INF] LNWL: Rescanned through block 00000000000000433e733604da24785581e772a10c7b652c4f453520895fd7fc (height 1413010)

[18:31:35.904] [info] lnd: 2018-10-08 18:31:35.904 [INF] BTCN: Fetching set of checkpointed cfheaders filters from height=1416000, hash=84b5869602dfe136b2802d45491af23a22e3e16fcaac754c84ce36d2727a2395
2018-10-08 18:31:35.904 [INF] BTCN: Starting to query for cfheaders from checkpoint_interval=1416

[18:31:36.802] [info] GRPC unlockerClosed
[18:31:36.809] [info] GRPC lndReady
[18:31:36.822] [info] lnd: 2018-10-08 18:31:36.820 [INF] RPCS: [listchannels] fetched 0 channels from DB

[18:31:37.499] [info] Saved state
[18:31:53.049] [info] lnd: 2018-10-08 18:31:53.047 [INF] BTCN: Attempting to query for 8 cfheader batches
2018-10-08 18:31:53.047 [INF] RPCS: [newaddress] addr=2NEESubrLbDg2QeGpNiDrpCGx3xv1QqaMaU

[18:31:54.681] [info] lnd: 2018-10-08 18:31:54.680 [INF] BTCN: Processed 2001 blocks in the last 22.62s (height 1426886, 2018-10-07 19:09:35 -0300 -03)

[18:32:10.877] [info] lnd: 2018-10-08 18:32:10.876 [INF] BTCN: Verified 1 filter header in the last 38.82s (height 1416001, 2018-10-07 14:13:17 -0300 -03)

[18:32:12.860] [info] lnd: 2018-10-08 18:32:12.860 [INF] BTCN: Processed 2000 blocks in the last 18.17s (height 1428886, 2018-10-07 21:06:58 -0300 -03)

[18:32:27.756] [info] lnd: 2018-10-08 18:32:27.755 [INF] BTCN: Verified 1000 filter headers in the last 16.87s (height 1417001, 2018-10-07 14:25:42 -0300 -03)

[18:32:27.766] [error] lnd Error: panic: couldn't write cfheaders msg: attempt to write cfheaders out of order

goroutine 58 [running]:
github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino.(*blockManager).getCheckpointedCFHeaders.func1(0xc4204860a0, 0x11c09c0, 0xc4205b56e0, 0x11c0780, 0xc420d83140, 0x1)
	/home/travis/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino/blockmanager.go:946 +0xade

[18:32:27.767] [error] lnd Error: github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino.(*ChainService).queryBatch(0xc42048a500, 0xc42057c000, 0x8, 0x590, 0xc4219a9940, 0xc42036c060, 0x0, 0x0, 0x0)
	/home/travis/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino/query.go:422 +0xa85
github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino.(*blockManager).getCheckpointedCFHeaders(0xc4205e2000, 0xc420984000, 0x590, 0x6a0, 0xc42000e090, 0x500)
	/home/travis/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino/blockmanager.go:849 +0x983
github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino.(*blockManager).cfHandler(0xc4205e2000)
	/home/travis/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino/blockmanager.go:560 +0xda6
created by github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino.(*blockManager).Start
	/home/travis/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/lightninglabs/neutrino/blockmanager.go:251 +0x107

[18:32:27.782] [info] Transactions update: [object Object]
[18:32:27.783] [info] Invoices update: [object Object]
[18:32:28.213] [error] Getting channel balance failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[18:32:28.216] [error] Getting wallet balance failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[18:32:29.211] [error] Getting node info failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[18:32:31.070] [error] Getting node info failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[18:32:31.073] [error] Getting channel balance failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[18:32:31.075] [error] Getting wallet balance failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[18:32:33.418] [error] Getting channel balance failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[18:32:33.420] [error] Getting wallet balance failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[18:32:33.423] [error] Getting node info failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[18:32:37.616] [error] Getting node info failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[18:32:37.618] [error] Getting channel balance failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[18:32:37.620] [error] Getting wallet balance failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[18:32:43.741] [error] Getting channel balance failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[18:32:43.744] [error] Getting wallet balance failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[18:32:43.747] [error] Getting node info failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[18:32:54.839] [error] Getting node info failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[18:32:54.842] [error] Getting channel balance failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[18:32:54.845] [error] Getting wallet balance failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[18:33:11.108] [error] Getting channel balance failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[18:33:11.112] [error] Getting wallet balance failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[18:33:11.114] [error] Getting node info failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[18:33:33.162] [error] Getting node info failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[18:33:33.165] [error] Getting channel balance failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[18:33:33.166] [error] Getting wallet balance failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[18:34:10.999] [error] Getting channel balance failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[18:34:11.002] [error] Getting wallet balance failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[18:34:11.004] [error] Getting node info failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[18:35:13.382] [error] Getting node info failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[18:35:13.386] [error] Getting channel balance failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }
[18:35:13.387] [error] Getting wallet balance failed { code: 14,
  details: 'Connect Failed',
  metadata: { _internal_repr: {} } }

**Comment by Roasbeef** [comment]
Will be tracking at https://github.com/lightninglabs/neutrino/issues/100
