### ISSUE TITLE
panic in GetUtxo

### ISSUE THREAD

**Issue by ksedgwic** [lightninglabs/lightning-app#87]
### Description
After starting the client I receive a panic in the log:
```
2017-11-07 11:26:07.385 [INF] NTFN: Cancelling spend notification for out_point=86519563f05353212bdb92b89b5954ef22c97ec29d822c139099d33e5ec48c81:0, spend_id=6
2017-11-07 11:26:07.386 [INF] HSWC: ChannelLink(86519563f05353212bdb92b89b5954ef22c97ec29d822c139099d33e5ec48c81:0) has exited
2017-11-07 11:26:07.386 [INF] NTFN: Cancelling epoch notification, epoch_id=4
[11:26:07:0555] [error] lnd: panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xa85641]

goroutine 250 [running]:
github.com/lightningnetwork/lnd/lnwallet/btcwallet.(*BtcWallet).GetUtxo(0xc430516900, 0xc4201f4540, 0xc400123ff8, 0x0, 0x0, 0x1)
	/Users/bryanvu/work/src/github.com/lightningnetwork/lnd/lnwallet/btcwallet/blockchain.go:68 +0x3f1
github.com/lightningnetwork/lnd/routing.(*ChannelRouter).processUpdate(0xc42000f760, 0xc87960, 0xc4204f63c0, 0xc420768c01, 0x0)
	/Users/bryanvu/work/src/github.com/lightningnetwork/lnd/routing/router.go:807 +0xf5a
github.com/lightningnetwork/lnd/routing.(*ChannelRouter).networkHandler(0xc42000f760)
	/Users/bryanvu/work/src/github.com/lightningnetwork/lnd/routing/router.go:476 +0x1eb
created by github.com/lightningnetwork/lnd/routing.(*ChannelRouter).Start
	/Users/bryanvu/work/src/github.com/lightningnetwork/lnd/routing/router.go:297 +0x353

Caught Main Process Error: { Error: Endpoint read failed
    at ClientReadableStream._emitStatusIfDone (/home/ksedgwic/bonsai/Lightning-linux-x64/resources/app/node_modules/grpc/src/node/src/client.js:270:19)
    at ClientReadableStream._receiveStatus (/home/ksedgwic/bonsai/Lightning-linux-x64/resources/app/node_modules/grpc/src/node/src/client.js:248:8)
    at /home/ksedgwic/bonsai/Lightning-linux-x64/resources/app/node_modules/grpc/src/node/src/client.js:720:12 code: 14, metadata: Metadata { _internal_repr: {} } }
[11:26:07:0579] [error] Main Process: Error: Endpoint read failed
Caught Main Process Error: { Error: Endpoint read failed
    at ClientReadableStream._emitStatusIfDone (/home/ksedgwic/bonsai/Lightning-linux-x64/resources/app/node_modules/grpc/src/node/src/client.js:270:19)
    at ClientReadableStream._receiveStatus (/home/ksedgwic/bonsai/Lightning-linux-x64/resources/app/node_modules/grpc/src/node/src/client.js:248:8)
    at /home/ksedgwic/bonsai/Lightning-linux-x64/resources/app/node_modules/grpc/src/node/src/client.js:720:12 code: 14, metadata: Metadata { _internal_repr: {} } }
[11:26:07:0580] [error] Main Process: Error: Endpoint read failed
```

### Steps to reproduce the behavior

Start the client.

My platform is:
```
[ksedgwic@lap4 Desktop]$ uname -a
Linux lap4.bonsai.com 4.13.9-200.fc26.x86_64 #1 SMP Mon Oct 23 13:52:45 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
[ksedgwic@lap4 Desktop]$ cat /etc/redhat-release 
Fedora release 26 (Twenty Six)
```

### Expected behavior

Start, not crash.

### Actual behavior

Crash.

### Screenshot and/or logs if applicable
```
[ksedgwic@lap4 Lightning-linux-x64]$     ./Lightning
^Z
[1]+  Stopped                 ./Lightning
[ksedgwic@lap4 Lightning-linux-x64]$ bg
[1]+ ./Lightning &
[ksedgwic@lap4 Lightning-linux-x64]$     tail -F $LNDHOME/logs/testnet3/bitcoin/lnd.log
2017-11-07 11:24:41.555 [INF] LNWL: Done catching up block hashes
2017-11-07 11:24:41.555 [INF] LNWL: Finished rescan for 40 addresses (synced to block 000000000000e86ed2844aec23e06bcfadbea88d5e718acf22de0ff24d13d44d, height 1225853)
2017-11-07 11:24:41.557 [INF] RPCS: RPC server listening on 127.0.0.1:10009
2017-11-07 11:24:41.557 [INF] LTND: Waiting for chain backend to finish sync, start_height=1225853
2017-11-07 11:24:41.557 [INF] LTND: Chain backend is fully synced (end_height=1225853)!
2017-11-07 11:24:41.557 [INF] HSWC: Starting HTLC Switch
2017-11-07 11:24:41.557 [INF] RPCS: gRPC proxy started at localhost:8080
2017-11-07 11:24:41.557 [INF] NTFN: New block epoch subscription
2017-11-07 11:24:41.559 [INF] BRAR: Retrieved 4 channels from database, watching with vigilance!
2017-11-07 11:24:41.560 [INF] NTFN: New spend notification for outpoint=7052412adce3a343b0d3dcd1da8b82d6dd9c5e535390e0767ecd7f675e9e4eca:0, height_hint=1210835
2017-11-07 11:24:53.800 [INF] NTFN: New spend notification for outpoint=13891fc6d370e8cd03d30298b6de851790d52a58c1b9ab2b0c4f4a1ed9dbcb34:0, height_hint=1210836
2017-11-07 11:24:53.800 [INF] NTFN: New spend subscription: utxo=7052412adce3a343b0d3dcd1da8b82d6dd9c5e535390e0767ecd7f675e9e4eca:0
2017-11-07 11:24:53.800 [INF] LNWL: Close observer for ChannelPoint(7052412adce3a343b0d3dcd1da8b82d6dd9c5e535390e0767ecd7f675e9e4eca:0) active
2017-11-07 11:25:02.334 [INF] RPCS: [listchannels] fetched 4 channels from DB
2017-11-07 11:25:02.371 [INF] RPCS: [listchannels] fetched 4 channels from DB
2017-11-07 11:25:05.968 [INF] LNWL: Close observer for ChannelPoint(13891fc6d370e8cd03d30298b6de851790d52a58c1b9ab2b0c4f4a1ed9dbcb34:0) active
2017-11-07 11:25:05.968 [INF] NTFN: New spend notification for outpoint=86519563f05353212bdb92b89b5954ef22c97ec29d822c139099d33e5ec48c81:0, height_hint=1210882
2017-11-07 11:25:05.968 [INF] NTFN: New spend subscription: utxo=13891fc6d370e8cd03d30298b6de851790d52a58c1b9ab2b0c4f4a1ed9dbcb34:0
2017-11-07 11:25:18.136 [INF] LNWL: Close observer for ChannelPoint(86519563f05353212bdb92b89b5954ef22c97ec29d822c139099d33e5ec48c81:0) active
2017-11-07 11:25:18.136 [INF] NTFN: New spend notification for outpoint=1e5b27d8661a9437d9ff85c69643442af9d107940c269721724b42801fb3128a:0, height_hint=1210834
2017-11-07 11:25:18.136 [INF] NTFN: New spend subscription: utxo=86519563f05353212bdb92b89b5954ef22c97ec29d822c139099d33e5ec48c81:0
2017-11-07 11:25:22.376 [INF] RPCS: [listchannels] fetched 4 channels from DB
2017-11-07 11:25:30.308 [INF] DISC: Authenticated Gossiper is starting
2017-11-07 11:25:30.308 [INF] LNWL: Close observer for ChannelPoint(1e5b27d8661a9437d9ff85c69643442af9d107940c269721724b42801fb3128a:0) active
2017-11-07 11:25:30.308 [INF] NTFN: New spend subscription: utxo=1e5b27d8661a9437d9ff85c69643442af9d107940c269721724b42801fb3128a:0
2017-11-07 11:25:30.308 [INF] NTFN: New block epoch subscription
2017-11-07 11:25:30.308 [INF] CRTR: FilteredChainView starting
2017-11-07 11:25:30.309 [INF] CRTR: Filtering chain using 523 channels active
2017-11-07 11:25:30.309 [INF] CRTR: Prune tip for Channel Graph: height=0, hash=<nil>
2017-11-07 11:25:30.313 [INF] SRVR: Initializing peer network boostrappers!
2017-11-07 11:25:30.313 [INF] SRVR: Creating DNS peer boostrapper with seeds: [[nodes.lightning.directory soa.nodes.lightning.directory]]
2017-11-07 11:25:30.313 [INF] ATPL: Instantiating autopilot with cfg: (*main.autoPilotConfig)(0xc4204e7260)({
 Active: (bool) true,
 MaxChannels: (int) 5,
 Allocation: (float64) 0.6
})

2017-11-07 11:25:30.313 [INF] CMGR: Server listening on [::]:9735
2017-11-07 11:25:30.313 [INF] DISC: Attempting to bootstrap with: Authenticated Channel Graph
2017-11-07 11:25:30.315 [INF] ATPL: Autopilot Agent starting
2017-11-07 11:25:30.315 [INF] ATPL: Processing new external signal
2017-11-07 11:25:30.315 [INF] ATPL: Triggering attachment directive dispatch
2017-11-07 11:25:30.318 [INF] DISC: Obtained 7 addrs to bootstrap network with
2017-11-07 11:25:30.319 [ERR] SRVR: unable to connect to 02827016f6f12382641289d316e0b93cd06fee72500145b4f099ccf2f01406bd98@127.0.0.1:9730: dial tcp 127.0.0.1:9730: getsockopt: connection refused
2017-11-07 11:25:30.399 [ERR] SRVR: unable to connect to 02aff94ad3c6879a63a2c561da705234fc9b9b934313394831c1ecea69f853d562@209.152.221.90:9735: dial tcp 209.152.221.90:9735: getsockopt: connection refused
2017-11-07 11:25:30.408 [ERR] SRVR: unable to connect to 02aff94ad3c6879a63a2c561da705234fc9b9b934313394831c1ecea69f853d562@24.12.185.155:9735: dial tcp 24.12.185.155:9735: getsockopt: connection refused
2017-11-07 11:25:30.447 [INF] ATPL: Attempting to execute channel attachment directives: ([]autopilot.AttachmentDirective) (len=1 cap=1) {
 (autopilot.AttachmentDirective) {
  PeerKey: (*btcec.PublicKey)(0xc4206fc7c0)({
   Curve: (elliptic.Curve) <nil>,
   X: (*big.Int)(0xc420218320)(506105415873312887320797103888759062905789797552414903650548125853814320429),
   Y: (*big.Int)(0xc420218340)(65515320114647690708763470620015028633316263056194936348320130649215163139197)
  }),
  ChanAmt: (btcutil.Amount) 0.04337254 BTC,
  Addrs: ([]net.Addr) (len=1 cap=1) {
   (*net.TCPAddr)(0xc420592720)(45.77.115.33:9735)
  }
 }
}

2017-11-07 11:25:30.525 [INF] SRVR: Established connection to: 104.131.26.124:9735
2017-11-07 11:25:30.627 [WRN] ATPL: Unable to open channel to 03011e720d36ebc549a19591f388a58918dd35b9f5507bc41bcef6a0f481176d2d of 0.04337254 BTC: Unable to connect to 03011e720d36ebc549a19591f388a58918dd35b9f5507bc41bcef6a0f481176d2d
2017-11-07 11:25:30.684 [INF] SRVR: Established connection to: 52.18.61.50:9735
2017-11-07 11:25:30.872 [INF] NTFN: New spend notification for outpoint=1e5b27d8661a9437d9ff85c69643442af9d107940c269721724b42801fb3128a:0, height_hint=1210834
2017-11-07 11:25:42.377 [INF] RPCS: [listchannels] fetched 4 channels from DB
2017-11-07 11:25:43.041 [INF] PEER: peerID(2) loading ChannelPoint(1e5b27d8661a9437d9ff85c69643442af9d107940c269721724b42801fb3128a:0)
2017-11-07 11:25:43.041 [INF] BRAR: ChannelPoint(1e5b27d8661a9437d9ff85c69643442af9d107940c269721724b42801fb3128a:0) is now live, abandoning state contract for live version
2017-11-07 11:25:43.041 [INF] LNWL: Close observer for ChannelPoint(1e5b27d8661a9437d9ff85c69643442af9d107940c269721724b42801fb3128a:0) active
2017-11-07 11:25:43.041 [INF] NTFN: New spend subscription: utxo=1e5b27d8661a9437d9ff85c69643442af9d107940c269721724b42801fb3128a:0
2017-11-07 11:25:43.041 [INF] NTFN: Cancelling spend notification for out_point=1e5b27d8661a9437d9ff85c69643442af9d107940c269721724b42801fb3128a:0, spend_id=4
2017-11-07 11:25:43.041 [INF] NTFN: New block epoch subscription
2017-11-07 11:25:43.048 [INF] HSWC: ChannelLink(1e5b27d8661a9437d9ff85c69643442af9d107940c269721724b42801fb3128a:0) is starting
2017-11-07 11:25:43.048 [INF] HSWC: Added channel link with chan_id=8a12b31f80424b722197260c9407d1f92a444396c685ffd937941a66d8275b1e, short_chan_id=((lnwire.ShortChannelID) {
 BlockHeight: (uint32) 1210834,
 TxIndex: (uint32) 77,
 TxPosition: (uint16) 0
}
), bandwidth=16768528000 mSAT
2017-11-07 11:25:43.048 [INF] SRVR: Established connection to: 34.250.234.192:9735
2017-11-07 11:25:43.048 [INF] HSWC: HTLC manager for ChannelPoint(1e5b27d8661a9437d9ff85c69643442af9d107940c269721724b42801fb3128a:0) started, bandwidth=16768528000 mSAT
2017-11-07 11:25:43.050 [INF] NTFN: New spend notification for outpoint=86519563f05353212bdb92b89b5954ef22c97ec29d822c139099d33e5ec48c81:0, height_hint=1210882
2017-11-07 11:26:02.373 [INF] RPCS: [listchannels] fetched 4 channels from DB
2017-11-07 11:26:07.378 [INF] PEER: peerID(3) loading ChannelPoint(86519563f05353212bdb92b89b5954ef22c97ec29d822c139099d33e5ec48c81:0)
2017-11-07 11:26:07.378 [INF] LNWL: Close observer for ChannelPoint(86519563f05353212bdb92b89b5954ef22c97ec29d822c139099d33e5ec48c81:0) active
2017-11-07 11:26:07.378 [INF] BRAR: ChannelPoint(86519563f05353212bdb92b89b5954ef22c97ec29d822c139099d33e5ec48c81:0) is now live, abandoning state contract for live version
2017-11-07 11:26:07.378 [INF] NTFN: New spend subscription: utxo=86519563f05353212bdb92b89b5954ef22c97ec29d822c139099d33e5ec48c81:0
2017-11-07 11:26:07.379 [INF] NTFN: New block epoch subscription
2017-11-07 11:26:07.379 [INF] NTFN: Cancelling spend notification for out_point=86519563f05353212bdb92b89b5954ef22c97ec29d822c139099d33e5ec48c81:0, spend_id=3
2017-11-07 11:26:07.385 [INF] HSWC: ChannelLink(86519563f05353212bdb92b89b5954ef22c97ec29d822c139099d33e5ec48c81:0) is starting
2017-11-07 11:26:07.385 [INF] HSWC: Added channel link with chan_id=818cc45e3ed39990132c829dc27ec922ef54599bb892db2b215353f063955186, short_chan_id=((lnwire.ShortChannelID) {
 BlockHeight: (uint32) 1210882,
 TxIndex: (uint32) 33,
 TxPosition: (uint16) 0
}
), bandwidth=16768528000 mSAT
2017-11-07 11:26:07.385 [INF] HSWC: HTLC manager for ChannelPoint(86519563f05353212bdb92b89b5954ef22c97ec29d822c139099d33e5ec48c81:0) started, bandwidth=16768528000 mSAT
2017-11-07 11:26:07.385 [INF] PEER: unable to read message from 34.250.234.192:9735: unknown message type [136]
2017-11-07 11:26:07.385 [INF] HSWC: Removing channel link with ChannelID(818cc45e3ed39990132c829dc27ec922ef54599bb892db2b215353f063955186)
2017-11-07 11:26:07.385 [INF] HSWC: ChannelLink(86519563f05353212bdb92b89b5954ef22c97ec29d822c139099d33e5ec48c81:0) is stopping
2017-11-07 11:26:07.385 [INF] NTFN: Cancelling spend notification for out_point=86519563f05353212bdb92b89b5954ef22c97ec29d822c139099d33e5ec48c81:0, spend_id=6
2017-11-07 11:26:07.386 [INF] HSWC: ChannelLink(86519563f05353212bdb92b89b5954ef22c97ec29d822c139099d33e5ec48c81:0) has exited
2017-11-07 11:26:07.386 [INF] NTFN: Cancelling epoch notification, epoch_id=4
[11:26:07:0555] [error] lnd: panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xa85641]

goroutine 250 [running]:
github.com/lightningnetwork/lnd/lnwallet/btcwallet.(*BtcWallet).GetUtxo(0xc430516900, 0xc4201f4540, 0xc400123ff8, 0x0, 0x0, 0x1)
	/Users/bryanvu/work/src/github.com/lightningnetwork/lnd/lnwallet/btcwallet/blockchain.go:68 +0x3f1
github.com/lightningnetwork/lnd/routing.(*ChannelRouter).processUpdate(0xc42000f760, 0xc87960, 0xc4204f63c0, 0xc420768c01, 0x0)
	/Users/bryanvu/work/src/github.com/lightningnetwork/lnd/routing/router.go:807 +0xf5a
github.com/lightningnetwork/lnd/routing.(*ChannelRouter).networkHandler(0xc42000f760)
	/Users/bryanvu/work/src/github.com/lightningnetwork/lnd/routing/router.go:476 +0x1eb
created by github.com/lightningnetwork/lnd/routing.(*ChannelRouter).Start
	/Users/bryanvu/work/src/github.com/lightningnetwork/lnd/routing/router.go:297 +0x353

Caught Main Process Error: { Error: Endpoint read failed
    at ClientReadableStream._emitStatusIfDone (/home/ksedgwic/bonsai/Lightning-linux-x64/resources/app/node_modules/grpc/src/node/src/client.js:270:19)
    at ClientReadableStream._receiveStatus (/home/ksedgwic/bonsai/Lightning-linux-x64/resources/app/node_modules/grpc/src/node/src/client.js:248:8)
    at /home/ksedgwic/bonsai/Lightning-linux-x64/resources/app/node_modules/grpc/src/node/src/client.js:720:12 code: 14, metadata: Metadata { _internal_repr: {} } }
[11:26:07:0579] [error] Main Process: Error: Endpoint read failed
Caught Main Process Error: { Error: Endpoint read failed
    at ClientReadableStream._emitStatusIfDone (/home/ksedgwic/bonsai/Lightning-linux-x64/resources/app/node_modules/grpc/src/node/src/client.js:270:19)
    at ClientReadableStream._receiveStatus (/home/ksedgwic/bonsai/Lightning-linux-x64/resources/app/node_modules/grpc/src/node/src/client.js:248:8)
    at /home/ksedgwic/bonsai/Lightning-linux-x64/resources/app/node_modules/grpc/src/node/src/client.js:720:12 code: 14, metadata: Metadata { _internal_repr: {} } }
[11:26:07:0580] [error] Main Process: Error: Endpoint read failed
```

**Comment by ksedgwic** [comment]
This was version Lightning-linux-x64v0.1.2.tar.gz

**Comment by ksedgwic** [comment]
now I know what "close and comment" means ...

**Comment by Roasbeef** [comment]
Did you have an existing installation of the application before you upgraded?

**Comment by aakselrod** [comment]
While the fix above will prevent a panic, the BIP-compliant `lnd` client will still not behave correctly if run with `neutrino` data generated by a pre-BIP-compliant version.

**Comment by Roasbeef** [comment]
Closing as the latest release includes the fix linked above (was due to not being updated to the latest filter format).
